### ISSUE TITLE
Implement DECIMAL type

### ISSUE THREAD

**Issue by quux00** [istreamdata/orientgo#12]
ogonori currently has not support for the OrientDB DECIMAL type.

Support that needs to be added includes:

* *deserialization* according to http://orientdb.com/docs/last/orientdb.wiki/Record-Schemaless-Binary-Serialization.html
* *serialization* according to http://orientdb.com/docs/last/orientdb.wiki/Record-Schemaless-Binary-Serialization.html
* some representation of the type to the user - do we need an `ODecimal` type in the oschema package?

Some restrictions:

- I only want the DECIMAL functionality needed by OrientDB. I do not want a general purpose `BigInteger` class implemented
- I do not want to bring in a dependency on a 3rd part BigInt or BigDecimal style class.  It is my goal to make ogonori dependency-free, except for the Go stdlib

**Comment by dennwc** [comment]
DECIMAL is supported as [big.Int](http://golang.org/pkg/math/big/#Int) Go type in [v2](https://github.com/istreamdata/orientgo/tree/v2) branch. Still need to support [big.Float](http://golang.org/pkg/math/big/#Float) for Go 1.5 and fallback to custom implementation for Go 1.4 (or something like [big.Rat](http://golang.org/pkg/math/big/#Rat)).

**Comment by dennwc** [comment]
Will use `big.Int` and `orient.Decimal` for now.
