### ISSUE TITLE
Can you insert a struct without using a command?

### ISSUE THREAD

**Issue by josebalius** [istreamdata/orientgo#29]
I tried playing around with the Document type but could not figure out a way to simply insert a struct without writing an insert statement. 

I realize this is more "ORM" but I was wondering if it was currently possible?

Thanks!

Jose

**Comment by dennwc** [comment]
Hi, @josebalius!

This is related to #27. I intend to implement a way to convert a structs to Documents shortly, and this will allow to write something like this:

``` Go
var a MyStruct
doc := orient.ToDocument(a)
db.CreateRecord(doc)
```

Is that a behavior you asking about?

The long way in example above is intentional, as it allows to set a RID on Document (this changes default cluster of a record). After some time I will also implement a way to register Go structs as a class for OrientDB, using fields to set type constraint, allowing to just insert a struct to certain cluster. This will be more ORM-like :)

**Comment by josebalius** [comment]
@dennwc yep exactly what I mean, that would be awesome!

**Comment by dennwc** [comment]
Implemented. First step to #6. `Document.From` function can be used in this way:

``` Go
var a MyStruct
doc := orient.NewDocument("Structs") // cluster or class name
_ = doc.From(a) // can return conversion error
err := db.CreateRecord(doc) // doc will be updated with new record RID and version

a.Data = "some changes"
doc.From(a) // fill doc with changes
err = db.UpdateRecord(doc) // version will be updated
```

@josebalius feel free to reopen this issue if you have any related questions or proposals

**Comment by josebalius** [comment]
@dennwc So it looks like it can't convert structs that have consts with iota on them (go enums) :/ What do you recommend I do? Need an example or you know what I mean?

**Comment by ympons** [comment]
@josebalius I suspect the problem is not the struct. You was using a custom type `SourceType` (https://github.com/istreamdata/orientgo/issues/37), so the type was unknown for the serializer.

**Comment by josebalius** [comment]
@ympons yes, its the custom type but is there anyway to support this? otherwise the enum pattern recommended by Go won't ever be compatible with this. I guess i can just use "int" as my type but that makes me sad :(

**Comment by josebalius** [comment]
Maybe we could use a struct tag to specify how to convert the custom type? It's just an int at the end of the day.

**Comment by dennwc** [comment]
This is not a big problem. It only needs a small tweak in a type converter. I will check it tomorrow. Also, please open a new issue for that, or reopen issue #37.

**Comment by josebalius** [comment]
@dennwc Can you please provide an example on how to use the `UpdateRecord` API without doing a `CreateRecord` first? All of the examples I found in the code were after a `CreateRecord` has been done and I am having some trouble updating a record that i got from a query.

**Comment by josebalius** [comment]
@dennwc I keep getting `record is not persistent`

```
doc := orient.NewDocument("DataSources")
            doc.From(ds)
            ds.Columns = columns
            //doc.SetField("columns", columns)
            err := m.UpdateRecord(doc)

            log.Println(ds)
log.Println(ds.RID.IsPersistent()) // true

            if err != nil {
                panic(err)
            }
```

`ds` is a struct that got filled out from a query

**Comment by josebalius** [comment]
So I added `doc.SetRID(ds.RID)` to the code and that seemed to do it

**Comment by dennwc** [comment]
Right, Document.RID is the only way for now to determine which record to update. Related to https://github.com/istreamdata/orientgo/issues/32 .
