### ISSUE TITLE
Check if class exists

### ISSUE THREAD

**Issue by josebalius** [istreamdata/orientgo#36]
Is this possible to do with this library? 

Here is an example on how to do it with Java: https://groups.google.com/forum/#!topic/orient-database/qaZHIc-gb2E so I guess my question is, is there anyway to load metadata/schema for the database to check if a class exists?

Thanks!

**Comment by dennwc** [comment]
Yes, you can:

``` Go
var classes map[string]*orient.OClass
classes = db.GetCurDB().Classes
```

Note, that this function may be replaced later with another API. Also, keep in mind that you should call ReloadSchema to get actual results.

**Comment by josebalius** [comment]
@dennwc Thank you Denys, very helpful as always.
