### ISSUE TITLE
Create edge question

### ISSUE THREAD

**Issue by josebalius** [istreamdata/orientgo#42]
Why is this failing:

``` Go
    log.Println(p.RID.String()) // #18:4
    log.Println(s.RID.String()) // #19:4

    // create edge between profile -> source pointer
    c := m.Command(orient.NewSQLCommand("create edge ActiveEdges from ? to ?", p.RID.String(), s.RID.String()))
```

Error: `Argument '?' is not a RecordId in form of string. Format must be: <cluster-id>:<cluster-position>` do I have to parse out the `#` from the RID?

**Comment by dennwc** [comment]
Try to pass `p.RID` and `s.RID` directly, without `String` invocation

**Comment by josebalius** [comment]
I tried that at first :p but encountered the same error so tried string to see if it helped but same result

**Comment by dennwc** [comment]
What version of OrientDB you are using? I encountered such problems on 2.0 and the reason was in Orient itself, as it have not expected to see placeholder after TO and FROM keywords.

Anyway, this will do the job for any version:

``` Go
orient.NewSQLCommand(fmt.Sprintf("create edge ActiveEdges from %s to %s", p.RID, s.RID))
```

**Comment by josebalius** [comment]
@dennwc I'm sorry I was running 2.0.14......let me upgrade and report back.

**Comment by josebalius** [comment]
It seems to have gone away after upgrading, sorry about that.
