### ISSUE TITLE
OrientDB

### ISSUE THREAD

**Issue by ernestas-poskus** [istreamdata/orientgo#49]
@dennwc 

Merry Christmas and happy holidays :8ball: 

I have a question not related to driver though rather to OrientDB database itself.
Maybe you happen to encounter such error ?

> java.lang.IllegalArgumentException: Cluster 1095 is null

I have over 1000 clusters and sometimes cluster disappears magically. I have tried to google this problem but was not able to find any solid solution since you I believe are running this in production maybe you have any ideas ?

Appreciated.

**Comment by dennwc** [comment]
@ernestas-poskus Thanks, the same for you! :)

Sorry, but I haven't seen such kind of error before. Maybe this is somehow related to the way binary protocol works in OrientDB server. It is a "thick" client, thus there is an intermediate layer between database and the actual client. Maybe that layer looses cluster information for some reason. I think you should definitely open an issue for OrientDB server, they can tell how to receive additional debug info for this case.

**Comment by ernestas-poskus** [comment]
Will do that, thank anyway.
