### ISSUE TITLE
Take over ogonori?

### ISSUE THREAD

**Issue by quux00** [istreamdata/orientgo#5]
Hi everyone,

I am the creater/owner of the ogonori project.

@dennwc posted a note on the ogonori (https://github.com/quux00/ogonori) site about a fix you guys had made for a bug we've had.  Which led me to finding your fork and looking it over.  You've definitely made some excellent progress in the last few weeks.

I recently started a new job and haven't had much time to work on ogonori.  I actually spoke with Luca, the CEO of OrientDB and we considered having me join as a contractor to finish ogonori, but I ended up going another path.

Since you guys are making good progress on the project, I wonder if you are interested in "taking it over".  By which I mean, you can take the "ogonori" name if you like it and I will stop work on my repo and put a note on my README redirecting interested parties here.

Currently I have 61 stars and at least one person using it in "production" (though I don't really condone that since it is still so alpha), so you'd probably have some immediate adopters and maybe contributors.  Currently, I only have one very part time submitter to my project, so I think I can safely redirect all activity from mine to yours.  And once I get over the hump of the new job I'm at, I'd be interested in contributing to your repo.

Let me know what you think,
Michael Peterson

**Comment by dennwc** [comment]
Hi Michael,

First of all, thank you for great job of making ogonori. It was a good base to start. We used it for quite a long time with only few modifications. Later on we discovered some flaws and decided to fork repo and experiment with it. So, answering to your question - yes, we will continue to work on ogonori/orientgo further, as we use it for our projects. We also think that merge of two drivers is important to not let community shard on decision which driver to use.

Now, we have two ways:

1) You can change `README` to point to our repo. Doing this way will ensure, that no user code will be broken. The ones that have interest in updating their code to use newer driver will have to explicitly change the import path and adapt to API changes.

2) You can grant us permission in `ogonori` repo, or just transfer ownership of it, if you like. We will initiate a pull request with all of our changes, which can easily be merged, as branches have not diverged yet. User code will be hit by API change, as we changed method signatures in `obinary` package. But that's it - users still can call `obinary` low-level driver directly, or switch to more high-level `orient` API, which takes advantage of connection pool and some other convenient features. As an alternative we can use something like [gopkg.in](http://labix.org/gopkg.in) in order to freeze ogonori API as `v1` and not break anything except of import paths. Still, we can not continue "no dependencies" policy of ogonori, but we will try to narrow them or provide user with alternatives (in case of logging, for example).

**Comment by quux00** [comment]
Hi @dennwc,

Very glad to hear that you are interested in taking over ogonori.   

> We also think that merge of two drivers is important to not let community shard on decision which driver to use.

Totally agree.  Thanks for taking it over and merging the efforts.

In terms of logistics, the "Transfer Ownership" option in GitHub says:  
> Transfer this repository to another user or to an organization where you have admin rights

So I'm guessing it will fail if I try it? The option to make you admins/contributions to quux00/ogonori is probably better. Then you could initiate the transfer.

This evening I will put a tag on quux00/ogonori as "v1" and put a note on the README and put an issue out that it is being transferred.

> But that's it - users still can call obinary low-level driver directly, or switch to more high-level orient API,

Yes, that was my intention all along.  Build one (or more) high level APIs in the low level one - so that should be a transition that existing users are excited about.

> Still, we can not continue "no dependencies" policy of ogonori,

My primary intention there was to not have to change midstream how vendoring/packaging is done, since the Go community has not really settled on a standard way to do that.  It was a headache I didn't want to deal with, but once you've brought one 3p dependency in you can bring more in since solving it the first time is much harder than any subsequent time.  And since you've already solved it, then it's no problem.

Tomorrow I'll make you (@dennwc) and istreamdata admins/contributors to quux00/ogonori and you can initiate the transfer when it makes sense for you.

**Comment by dennwc** [comment]
Great, waiting for upcoming changes. You can transfer directly to @dyy18 as he have admin rights on our organization, and then he will transfer it to istreamdata itself.

From our side, merge will take some time, as I will try to minimize impact on existing code. Especially, I want to finish new serializer that I started few days ago and pull it into new repo, as current implementation in orientgo is too rough for release.

**Comment by quux00** [comment]
Sorry for the delay.  I have made both @dyy18 and @dennwc "collaborators" (as GitHub calls it) for the quux00/ogonori repo.  Let me know if this role has sufficient privileges for you to do the transfer/merger.  And let me know if you need anything from me in the process.  I should be more responsive this week than last.

**Comment by dennwc** [comment]
@quux00 collaborator role is ok for the merge, but is insufficient for transfer. It would be better if you can just transfer the ownership of a repo to @dyy18 and then fork it. Without owner permissions our team will not have such autonomy, as we have on our current repo.

**Comment by quux00** [comment]
OK.  I have started the transfer to @dyy18.  The feedback was: 
> Repository transfer to dyy18 requested

**Comment by dennwc** [comment]
Great, thanks!

We will switch repo to our organization on Monday and I will prepare everything for the merge.

There is one last question - the name of a repo. We'd like to call it `orient-go` as using something like `orient.Client` sounds better for us, but we can use `ogonori` if you have some strong preferences of calling it this way :)

**Comment by quux00** [comment]
> We'd like to call it orient-go as using something like orient.Client sounds better for us, but we can use ogonori

I'll leave it up to you, since you'll be doing the heavy lifting going forward :-) 

I'll just say why I like the ogonori name and you can take that under consideration.  

First, I think there is some weariness in the Go community of just "xxx-go" and "go-yyy" names.  As partial proof, see Rob Pike's recent tweet: https://twitter.com/rob_pike/status/618357610287226880

I also like names that have multiple "meanings" or nuances.  I originally wanted to name it "ogo", short for "orientdb-go", but there was already a project with that name.  Then I hit upon the idea that (to English speakers at least) "Orient" has another meaning as in "The Orient" - the Far East - Japan, China, Thailand, Korea, etc.  So I found that the word ogonori refers to a type of seaweed, popular in "The Orient" (Japan), so this is one tie between the name and "OrientDB".  And it slips in the word "go" but as part of a larger pre-existing word - a somewhat clever hack, as naming goes.

Finally, the name somewhat reminded me of "nokogiri"  a popular Ruby library that is named after Mount Nokogiri in Japan.  Unique names like that stick in my head, so it potentially makes the library stand out more than a more traditional name.

My intention was also to have a set of top level libraries that would `ogonori.Client`, etc, as you are doing.

But if you and your company prefer the clearer "orient" name, I can see the advantage of that as well.  So please choose the one that works best for you.

Thanks again for taking this forward.

**Comment by tnamoradze** [comment]
Hi Michael,
@dyy18 has holiday and is unreachable today. He can approve repository move only tomorrow evening (EET)

Cheers,
Temo

**Comment by dennwc** [comment]
@quux00 Please resend transfer request again, previous link expired)

**Comment by quux00** [comment]
OK, aborted previous transfer and restarted a new one.

**Comment by dennwc** [comment]
Thanks, we accepted transfer successfully. I'm closing issue and will start a merge shortly.
