### ISSUE TITLE
Ability to specify size of db connection pool during Open

### ISSUE THREAD

**Issue by RAndrews137** [istreamdata/orientgo#57]
Hi,

I noticed that the Open method for Client does not allow the pool size to be passed in.  It is using zero which cause it to use the default max connections (6).  Code listed below.  I would like to suggest an additional Open method where the user can provide the pool size.  Should be an easy change.  I could do it.  What is the process for getting PR approved (conventions, etc.)?

Thanks,
Ronnie

//current code
func (c _Client) Open(name string, dbType DatabaseType, user, pass string) (_Database, error) {
    db := &Database{pool: newConnPool(0, func() (DBSession, error) {

//suggestion

// Open initiates a new database session, allowing to make queries to selected database.
//
// For database management use Auth instead.
func (c _Client) Open(name string, dbType DatabaseType, user, pass string) (_Database, error) {
    return OpenWithPoolSize(name, dbType, user, pass, 0)
}

// Open initiates a new database session, allowing to make queries to selected database.
//
// For database management use Auth instead.
func (c _Client) OpenWithPoolSize(name string, dbType DatabaseType, user, pass string, poolSize int) (_Database, error) {
    db := &Database{pool: newConnPool(poolSize, func() (DBSession, error) {
        conn, err := c.dial()
        if err != nil {
            return nil, err
        }
        ds, err := conn.Open(name, dbType, user, pass)
        if err != nil {
            conn.Close()
            return nil, err
        }
        return sessionAndConn{DBSession: ds, conn: conn}, nil
    }), cli: c}
    conn, err := db.pool.getConn()
    if err != nil {
        return nil, err
    }
    db.pool.putConn(conn)
    return db, nil
}

**Comment by dennwc** [comment]
Hi @RAndrews137,

You can set a default pool size via [MaxConnections](https://github.com/istreamdata/orientgo/blob/b14c8a388dfb5150ba60aab53c564cda66396ea1/client.go#L33) variable.

**Comment by RAndrews137** [comment]
My apologies.  You are correct.  Closing this issue.
