### ISSUE TITLE
Implement Flat record type

### ISSUE THREAD

**Issue by quux00** [istreamdata/orientgo#8]
This is the data type 'f' as documented in the `REQUEST_RECORD_LOAD`, `REQUEST_RECORD_CREATE`, `REQUEST_RECORD_UPDATE` sections of http://orientdb.com/docs/last/Network-Binary-Protocol.html

Currently there is a stub function in obinary/qrycmd.go:

    //
    // TODO: need example from server to know how to handle this
    //
    func readFlatDataRecord(dbc *DBClient) (*oschema.ODocument, error) {
    	ogl.Warnf("flat record ('f') record type -> haven't seen that before. What is it?")
    	return nil, errors.New("flat record ('f') record type -> haven't seen that before. What is it?")
    }

Fill this in.

There will likely also need to be a function for writing/serializing it.  There is currently no stub for that, since the data type is not yet understood.

The only hint I have is that one can specify type in a "content" clause of OrientDB SQL, like so:

    emb := `{"name": "Spotty", "age": 2, emb: {"@type": "d", "@class":"Cat", "name": "yowler", "age":13}}`
    retval, docs, err = obinary.SQLCommand(dbc, "insert into Cat content "+emb)
    Ok(err)

Here, the `emb` type is for a property/field of type EMBEDDED.  You can specify the 'd' (document) type
with `@type`.  Can we similarly specify 'f' with `@type`?  What types of data are allowed in "flat"?  Is it CSV?

**Comment by dennwc** [comment]
[ORecordFlat](https://github.com/orientechnologies/orientdb/blob/master/core/src/main/java/com/orientechnologies/orient/core/record/impl/ORecordFlat.java) in Java code. I noticed, that this record type is marked as deprecated, so maybe it will not be seen on wire at all.

**Comment by dennwc** [comment]
Haven't seen this record type on wire. Will not work on this until someone finds an example which involves Flat type.
