### ISSUE TITLE
Implement "raw bytes" record type

### ISSUE THREAD

**Issue by quux00** [istreamdata/orientgo#9]
This is the data type 'b' as documented in the `REQUEST_RECORD_LOAD`, `REQUEST_RECORD_CREATE`, `REQUEST_RECORD_UPDATE` sections of http://orientdb.com/docs/last/Network-Binary-Protocol.html

Currently there is a stub function in obinary/qrycmd.go:

    //
    // TODO: need example from server to know how to handle this
    //
    func readRawBytesRecord(dbc *DBClient) (*oschema.ODocument, error) {
    	ogl.Warnf("raw bytes ('b') record type -> haven't seen that before. Send to Deserializer?")
    	return nil, errors.New("raw bytes ('b') record type -> haven't seen that before. Send to Deserializer?")
    }

Fill this in.

There will likely also need to be a function for writing/serializing it.  There is currently no stub for that, since the data type is not yet understood.

The only hint I have is that one can specify type in a "content" clause of OrientDB SQL, like so:

    emb := `{"name": "Spotty", "age": 2, emb: {"@type": "d", "@class":"Cat", "name": "yowler", "age":13}}`
    retval, docs, err = obinary.SQLCommand(dbc, "insert into Cat content "+emb)
    Ok(err)

Here, the `emb` type is for a property/field of type EMBEDDED.  You can specify the 'd' (document) type
with `@type`.  Can we similarly specify 'b' with `@type`?  What types of data are allowed in "flat"?  Is it CSV?

In addition, how does "raw bytes" differ from the BINARY data type in a 'd' Document.  Is "raw bytes" the equiv of a relational DB blob?

**Comment by dennwc** [comment]
[ORecordBytes](https://github.com/orientechnologies/orientdb/blob/master/core/src/main/java/com/orientechnologies/orient/core/record/impl/ORecordBytes.java) in Java code. Handling of such records is already implemented in `v2` branch. Still need a way to send such records to DB, as this is a best way to store blobs in it.

**Comment by dennwc** [comment]
implemented via 8674733f657be79ce01ac29d8ddc476639337d72
